export { ReactComponent as IconCheckCircle } from './assets/check-circle.svg';
export { ReactComponent as IconCI } from './assets/CI.svg';
export { ReactComponent as IconDollar } from './assets/Dollar.svg';
export { ReactComponent as IconCompass } from './assets/compass.svg';
export { ReactComponent as IconCloseCircle } from './assets/close-circle.svg';
export { ReactComponent as IconFrown } from './assets/frown.svg';
export { ReactComponent as IconInfoCircle } from './assets/info-circle.svg';
export { ReactComponent as IconLeftCircle } from './assets/left-circle.svg';
export { ReactComponent as IconDownCircle } from './assets/down-circle.svg';
export { ReactComponent as IconEURO } from './assets/EURO.svg';
export { ReactComponent as IconCopyright } from './assets/copyright.svg';
export { ReactComponent as IconMinusCircle } from './assets/minus-circle.svg';
export { ReactComponent as IconMeh } from './assets/meh.svg';
export { ReactComponent as IconPlusCircle } from './assets/plus-circle.svg';
export { ReactComponent as IconPlayCircle } from './assets/play-circle.svg';
export { ReactComponent as IconQuestionCircle } from './assets/question-circle.svg';
export { ReactComponent as IconPound } from './assets/Pound.svg';
export { ReactComponent as IconRightCircle } from './assets/right-circle.svg';
export { ReactComponent as IconSmile } from './assets/smile.svg';
export { ReactComponent as IconTrademark } from './assets/trademark.svg';
export { ReactComponent as IconTimeCircle } from './assets/time-circle.svg';
export { ReactComponent as IconTimeOut } from './assets/time out.svg';
export { ReactComponent as IconEarth } from './assets/earth.svg';
export { ReactComponent as IconYUAN } from './assets/YUAN.svg';
export { ReactComponent as IconUpCircle } from './assets/up-circle.svg';
export { ReactComponent as IconWarningCircle } from './assets/warning-circle.svg';
export { ReactComponent as IconSync } from './assets/sync.svg';
export { ReactComponent as IconTransaction } from './assets/transaction.svg';
export { ReactComponent as IconUndo } from './assets/undo.svg';
export { ReactComponent as IconRedo } from './assets/redo.svg';
export { ReactComponent as IconReload } from './assets/reload.svg';
export { ReactComponent as IconReloadTime } from './assets/reload time.svg';
export { ReactComponent as IconMessage } from './assets/message.svg';
export { ReactComponent as IconDashboard } from './assets/dashboard.svg';
export { ReactComponent as IconIssuesClose } from './assets/issues close.svg';
export { ReactComponent as IconPoweroff } from './assets/poweroff.svg';
export { ReactComponent as IconLogout } from './assets/logout.svg';
export { ReactComponent as IconPieChart } from './assets/pie chart.svg';
export { ReactComponent as IconSetting } from './assets/setting.svg';
export { ReactComponent as IconEye } from './assets/eye.svg';
export { ReactComponent as IconLocation } from './assets/location.svg';
export { ReactComponent as IconEditSquare } from './assets/edit-square.svg';
export { ReactComponent as IconExport } from './assets/export.svg';
export { ReactComponent as IconSave } from './assets/save.svg';
export { ReactComponent as IconImport } from './assets/Import.svg';
export { ReactComponent as IconAppStore } from './assets/app store.svg';
export { ReactComponent as IconCloseSquare } from './assets/close-square.svg';
export { ReactComponent as IconDownSquare } from './assets/down-square.svg';
export { ReactComponent as IconLayout } from './assets/layout.svg';
export { ReactComponent as IconLeftSquare } from './assets/left-square.svg';
export { ReactComponent as IconPlaySquare } from './assets/play-square.svg';
export { ReactComponent as IconControl } from './assets/control.svg';
export { ReactComponent as IconCodeLibrary } from './assets/code library.svg';
export { ReactComponent as IconDetail } from './assets/detail.svg';
export { ReactComponent as IconMinusSquare } from './assets/minus-square.svg';
export { ReactComponent as IconPlusSquare } from './assets/plus-square.svg';
export { ReactComponent as IconRightSquare } from './assets/right-square.svg';
export { ReactComponent as IconProject } from './assets/project.svg';
export { ReactComponent as IconWallet } from './assets/wallet.svg';
export { ReactComponent as IconUpSquare } from './assets/up-square.svg';
export { ReactComponent as IconCalculator } from './assets/calculator.svg';
export { ReactComponent as IconInteration } from './assets/interation.svg';
export { ReactComponent as IconCheckSquare } from './assets/check-square.svg';
export { ReactComponent as IconBorder } from './assets/border.svg';
export { ReactComponent as IconBorderOuter } from './assets/border-outer.svg';
export { ReactComponent as IconBorderTop } from './assets/border-top.svg';
export { ReactComponent as IconBorderBottom } from './assets/border-bottom.svg';
export { ReactComponent as IconBorderLeft } from './assets/border-left.svg';
export { ReactComponent as IconBorderRight } from './assets/border-right.svg';
export { ReactComponent as IconBorderInner } from './assets/border-inner.svg';
export { ReactComponent as IconBorderVerticle } from './assets/border-verticle.svg';
export { ReactComponent as IconBorderHorizontal } from './assets/border-horizontal.svg';
export { ReactComponent as IconRadiusBottomleft } from './assets/radius-bottomleft.svg';
export { ReactComponent as IconRadiusBottomright } from './assets/radius-bottomright.svg';
export { ReactComponent as IconRadiusUpleft } from './assets/radius-upleft.svg';
export { ReactComponent as IconRadiusUpright } from './assets/radius-upright.svg';
export { ReactComponent as IconRadiusSetting } from './assets/radius-setting.svg';
export { ReactComponent as IconAddUser } from './assets/add user.svg';
export { ReactComponent as IconDeleteTeam } from './assets/delete team.svg';
export { ReactComponent as IconDeleteUser } from './assets/delete user.svg';
export { ReactComponent as IconAddteam } from './assets/addteam.svg';
export { ReactComponent as IconUser } from './assets/user.svg';
export { ReactComponent as IconTeam } from './assets/team.svg';
export { ReactComponent as IconAreaChart } from './assets/area chart.svg';
export { ReactComponent as IconLineChart } from './assets/line chart.svg';
export { ReactComponent as IconBarChart } from './assets/bar chart.svg';
export { ReactComponent as IconPointMap } from './assets/point map.svg';
export { ReactComponent as IconContainer } from './assets/container.svg';
export { ReactComponent as IconDatabase } from './assets/database.svg';
export { ReactComponent as IconSever } from './assets/sever.svg';
export { ReactComponent as IconMobile } from './assets/mobile.svg';
export { ReactComponent as IconTablet } from './assets/tablet.svg';
export { ReactComponent as IconRedEnvelope } from './assets/red envelope.svg';
export { ReactComponent as IconBook } from './assets/book.svg';
export { ReactComponent as IconFileDone } from './assets/file done.svg';
export { ReactComponent as IconReconciliation } from './assets/reconciliation.svg';
export { ReactComponent as IconFileException } from './assets/file -exception.svg';
export { ReactComponent as IconFileSync } from './assets/file sync.svg';
export { ReactComponent as IconFileSearch } from './assets/file search.svg';
export { ReactComponent as IconSolution } from './assets/solution.svg';
export { ReactComponent as IconFileProtect } from './assets/file protect.svg';
export { ReactComponent as IconFileAdd } from './assets/file-add.svg';
export { ReactComponent as IconFileExcel } from './assets/file-excel.svg';
export { ReactComponent as IconFileExclamation } from './assets/file-exclamation.svg';
export { ReactComponent as IconFilePdf } from './assets/file-pdf.svg';
export { ReactComponent as IconFileImage } from './assets/file-image.svg';
export { ReactComponent as IconFileMarkdown } from './assets/file-markdown.svg';
export { ReactComponent as IconFileUnknown } from './assets/file-unknown.svg';
export { ReactComponent as IconFilePpt } from './assets/file-ppt.svg';
export { ReactComponent as IconFileWord } from './assets/file-word.svg';
export { ReactComponent as IconFile } from './assets/file.svg';
export { ReactComponent as IconFileZip } from './assets/file-zip.svg';
export { ReactComponent as IconFileText } from './assets/file-text.svg';
export { ReactComponent as IconFileCopy } from './assets/file-copy.svg';
export { ReactComponent as IconSnippets } from './assets/snippets.svg';
export { ReactComponent as IconAudit } from './assets/audit.svg';
export { ReactComponent as IconDiff } from './assets/diff.svg';
export { ReactComponent as IconBatchFolding } from './assets/Batch folding.svg';
export { ReactComponent as IconSecurityScan } from './assets/security scan.svg';
export { ReactComponent as IconPropertySafety } from './assets/property safety.svg';
export { ReactComponent as IconSafetyCertificate } from './assets/safety certificate.svg';
export { ReactComponent as IconInsurance } from './assets/insurance.svg';
export { ReactComponent as IconAlert } from './assets/alert.svg';
export { ReactComponent as IconDelete } from './assets/delete.svg';
export { ReactComponent as IconHourglass } from './assets/hourglass.svg';
export { ReactComponent as IconBulb } from './assets/bulb.svg';
export { ReactComponent as IconExperiment } from './assets/experiment.svg';
export { ReactComponent as IconBell } from './assets/bell.svg';
export { ReactComponent as IconTrophy } from './assets/trophy.svg';
export { ReactComponent as IconRest } from './assets/rest.svg';
export { ReactComponent as IconUSB } from './assets/USB.svg';
export { ReactComponent as IconSkin } from './assets/skin.svg';
export { ReactComponent as IconHome } from './assets/home.svg';
export { ReactComponent as IconBank } from './assets/bank.svg';
export { ReactComponent as IconFilter } from './assets/filter.svg';
export { ReactComponent as IconFunnelPlot } from './assets/funnel plot.svg';
export { ReactComponent as IconLike } from './assets/like.svg';
export { ReactComponent as IconUnlike } from './assets/unlike.svg';
export { ReactComponent as IconUnlock } from './assets/unlock.svg';
export { ReactComponent as IconLock } from './assets/lock.svg';
export { ReactComponent as IconCustomerservice } from './assets/customerservice.svg';
export { ReactComponent as IconFlag } from './assets/flag.svg';
export { ReactComponent as IconMoneyCollect } from './assets/money collect.svg';
export { ReactComponent as IconMedicinebox } from './assets/medicinebox.svg';
export { ReactComponent as IconShop } from './assets/shop.svg';
export { ReactComponent as IconRocket } from './assets/rocket.svg';
export { ReactComponent as IconShopping } from './assets/shopping.svg';
export { ReactComponent as IconFolder } from './assets/folder.svg';
export { ReactComponent as IconFolderOpen } from './assets/folder-open.svg';
export { ReactComponent as IconFolderAdd } from './assets/folder-add.svg';
export { ReactComponent as IconDeploymentUnit } from './assets/deployment unit.svg';
export { ReactComponent as IconAccountBook } from './assets/account book.svg';
export { ReactComponent as IconContacts } from './assets/contacts.svg';
export { ReactComponent as IconCarryOut } from './assets/carry out.svg';
export { ReactComponent as IconCalendarCheck } from './assets/calendar-check.svg';
export { ReactComponent as IconCalendar } from './assets/calendar.svg';
export { ReactComponent as IconScan } from './assets/scan.svg';
export { ReactComponent as IconSelect } from './assets/select.svg';
export { ReactComponent as IconBoxPlot } from './assets/box plot.svg';
export { ReactComponent as IconBuild } from './assets/build.svg';
export { ReactComponent as IconSliders } from './assets/sliders.svg';
export { ReactComponent as IconLaptop } from './assets/laptop.svg';
export { ReactComponent as IconBarcode } from './assets/barcode.svg';
export { ReactComponent as IconCamera } from './assets/camera.svg';
export { ReactComponent as IconCluster } from './assets/cluster.svg';
export { ReactComponent as IconGateway } from './assets/gateway.svg';
export { ReactComponent as IconCar } from './assets/car.svg';
export { ReactComponent as IconPrinter } from './assets/printer.svg';
export { ReactComponent as IconRead } from './assets/read.svg';
export { ReactComponent as IconCloudServer } from './assets/cloud-server.svg';
export { ReactComponent as IconCloudUpload } from './assets/cloud-upload.svg';
export { ReactComponent as IconCloud } from './assets/cloud.svg';
export { ReactComponent as IconCloudDownload } from './assets/cloud-download.svg';
export { ReactComponent as IconCloudSync } from './assets/cloud-sync.svg';
export { ReactComponent as IconVideo } from './assets/video.svg';
export { ReactComponent as IconNotification } from './assets/notification.svg';
export { ReactComponent as IconSound } from './assets/sound.svg';
export { ReactComponent as IconRadarChart } from './assets/radar chart.svg';
export { ReactComponent as IconQrcode } from './assets/qrcode.svg';
export { ReactComponent as IconFund } from './assets/fund.svg';
export { ReactComponent as IconImage } from './assets/image.svg';
export { ReactComponent as IconMail } from './assets/mail.svg';
export { ReactComponent as IconTable } from './assets/table.svg';
export { ReactComponent as IconIdCard } from './assets/id card.svg';
export { ReactComponent as IconCreditCard } from './assets/credit card.svg';
export { ReactComponent as IconHeart } from './assets/heart.svg';
export { ReactComponent as IconBlock } from './assets/block.svg';
export { ReactComponent as IconError } from './assets/error.svg';
export { ReactComponent as IconStar } from './assets/star.svg';
export { ReactComponent as IconGold } from './assets/gold.svg';
export { ReactComponent as IconHeatMap } from './assets/heat map.svg';
export { ReactComponent as IconWifi } from './assets/wifi.svg';
export { ReactComponent as IconAttachment } from './assets/attachment.svg';
export { ReactComponent as IconEdit } from './assets/edit.svg';
export { ReactComponent as IconKey } from './assets/key.svg';
export { ReactComponent as IconApi } from './assets/api.svg';
export { ReactComponent as IconDisconnect } from './assets/disconnect.svg';
export { ReactComponent as IconHighlight } from './assets/highlight.svg';
export { ReactComponent as IconMonitor } from './assets/monitor.svg';
export { ReactComponent as IconLink } from './assets/link.svg';
export { ReactComponent as IconMan } from './assets/man.svg';
export { ReactComponent as IconPercentage } from './assets/percentage.svg';
export { ReactComponent as IconPushpin } from './assets/pushpin.svg';
export { ReactComponent as IconPhone } from './assets/phone.svg';
export { ReactComponent as IconShake } from './assets/shake.svg';
export { ReactComponent as IconTag } from './assets/tag.svg';
export { ReactComponent as IconWrench } from './assets/wrench.svg';
export { ReactComponent as IconTags } from './assets/tags.svg';
export { ReactComponent as IconScissor } from './assets/scissor.svg';
export { ReactComponent as IconMr } from './assets/mr.svg';
export { ReactComponent as IconShare } from './assets/share.svg';
export { ReactComponent as IconBranches } from './assets/branches.svg';
export { ReactComponent as IconFork } from './assets/fork.svg';
export { ReactComponent as IconShrink } from './assets/shrink.svg';
export { ReactComponent as IconArrawsalt } from './assets/arrawsalt.svg';
export { ReactComponent as IconVerticalRight } from './assets/vertical right.svg';
export { ReactComponent as IconVerticalLeft } from './assets/vertical left.svg';
export { ReactComponent as IconRight } from './assets/right.svg';
export { ReactComponent as IconLeft } from './assets/left.svg';
export { ReactComponent as IconUp } from './assets/up.svg';
export { ReactComponent as IconDown } from './assets/down.svg';
export { ReactComponent as IconFullscreen } from './assets/fullscreen.svg';
export { ReactComponent as IconFullscreenExit } from './assets/fullscreen-exit.svg';
export { ReactComponent as IconDoubleleft } from './assets/doubleleft.svg';
export { ReactComponent as IconDoubleRight } from './assets/double right.svg';
export { ReactComponent as IconArrowright } from './assets/arrowright.svg';
export { ReactComponent as IconArrowup } from './assets/arrowup.svg';
export { ReactComponent as IconArrowleft } from './assets/arrowleft.svg';
export { ReactComponent as IconArrowdown } from './assets/arrowdown.svg';
export { ReactComponent as IconUpload } from './assets/upload.svg';
export { ReactComponent as IconColumHeight } from './assets/colum-height.svg';
export { ReactComponent as IconVerticalAlignBotto } from './assets/vertical-align-botto.svg';
export { ReactComponent as IconVerticalAlignMiddl } from './assets/vertical-align-middl.svg';
export { ReactComponent as IconTotop } from './assets/totop.svg';
export { ReactComponent as IconVerticalAlignTop } from './assets/vertical-align-top.svg';
export { ReactComponent as IconDownload } from './assets/download.svg';
export { ReactComponent as IconSortDescending } from './assets/sort-descending.svg';
export { ReactComponent as IconSortAscending } from './assets/sort-ascending.svg';
export { ReactComponent as IconFall } from './assets/fall.svg';
export { ReactComponent as IconSwap } from './assets/swap.svg';
export { ReactComponent as IconStock } from './assets/stock.svg';
export { ReactComponent as IconRise } from './assets/rise.svg';
export { ReactComponent as IconIndent } from './assets/indent.svg';
export { ReactComponent as IconOutdent } from './assets/outdent.svg';
export { ReactComponent as IconMenu } from './assets/menu.svg';
export { ReactComponent as IconUnorderedList } from './assets/unordered list.svg';
export { ReactComponent as IconOrderedList } from './assets/ordered list.svg';
export { ReactComponent as IconAlignRight } from './assets/align-right.svg';
export { ReactComponent as IconAlignCenter } from './assets/align-center.svg';
export { ReactComponent as IconAlignLeft } from './assets/align-left.svg';
export { ReactComponent as IconPicCenter } from './assets/pic-center.svg';
export { ReactComponent as IconPicRight } from './assets/pic-right.svg';
export { ReactComponent as IconPicLeft } from './assets/pic-left.svg';
export { ReactComponent as IconBold } from './assets/bold.svg';
export { ReactComponent as IconFontColors } from './assets/font-colors.svg';
export { ReactComponent as IconExclaimination } from './assets/exclaimination.svg';
export { ReactComponent as IconFontSize } from './assets/font-size.svg';
export { ReactComponent as IconInfomation } from './assets/infomation.svg';
export { ReactComponent as IconLineHeight } from './assets/line-height.svg';
export { ReactComponent as IconStrikethrough } from './assets/strikethrough.svg';
export { ReactComponent as IconUnderline } from './assets/underline.svg';
export { ReactComponent as IconNumber } from './assets/number.svg';
export { ReactComponent as IconItalic } from './assets/italic.svg';
export { ReactComponent as IconCode } from './assets/code.svg';
export { ReactComponent as IconColumnWidth } from './assets/column-width.svg';
export { ReactComponent as IconCheck } from './assets/check.svg';
export { ReactComponent as IconEllipsis } from './assets/ellipsis.svg';
export { ReactComponent as IconDash } from './assets/dash.svg';
export { ReactComponent as IconClose } from './assets/close.svg';
export { ReactComponent as IconEnter } from './assets/enter.svg';
export { ReactComponent as IconLine } from './assets/line.svg';
export { ReactComponent as IconMinus } from './assets/minus.svg';
export { ReactComponent as IconQuestion } from './assets/question.svg';
export { ReactComponent as IconRollback } from './assets/rollback.svg';
export { ReactComponent as IconSmallDash } from './assets/small-dash.svg';
export { ReactComponent as IconPause } from './assets/pause.svg';
export { ReactComponent as IconBgColors } from './assets/bg-colors.svg';
export { ReactComponent as IconCrown } from './assets/crown.svg';
export { ReactComponent as IconDrag } from './assets/drag.svg';
export { ReactComponent as IconDesktop } from './assets/desktop.svg';
export { ReactComponent as IconGift } from './assets/gift.svg';
export { ReactComponent as IconStop } from './assets/stop.svg';
export { ReactComponent as IconFire } from './assets/fire.svg';
export { ReactComponent as IconThunderbolt } from './assets/thunderbolt.svg';
export { ReactComponent as IconCheckCircleFill } from './assets/check-circle-fill.svg';
export { ReactComponent as IconLeftCircleFill } from './assets/left-circle-fill.svg';
export { ReactComponent as IconDownCircleFill } from './assets/down-circle-fill.svg';
export { ReactComponent as IconMinusCircleFill } from './assets/minus-circle-fill.svg';
export { ReactComponent as IconCloseCircleFill } from './assets/close-circle-fill.svg';
export { ReactComponent as IconInfoCircleFill } from './assets/info-circle-fill.svg';
export { ReactComponent as IconUpCircleFill } from './assets/up-circle-fill.svg';
export { ReactComponent as IconRightCircleFill } from './assets/right-circle-fill.svg';
export { ReactComponent as IconPlusCircleFill } from './assets/plus-circle-fill.svg';
export { ReactComponent as IconQuestionCircleFill } from './assets/question-circle-fill.svg';
export { ReactComponent as IconEUROCircleFill } from './assets/EURO-circle-fill.svg';
export { ReactComponent as IconFrownFill } from './assets/frown-fill.svg';
export { ReactComponent as IconCopyrightCircleFil } from './assets/copyright-circle-fil.svg';
export { ReactComponent as IconCICircleFill } from './assets/CI-circle-fill.svg';
export { ReactComponent as IconCompassFill } from './assets/compass-fill.svg';
export { ReactComponent as IconDollarCircleFill } from './assets/Dollar-circle-fill.svg';
export { ReactComponent as IconPoweroffCircleFill } from './assets/poweroff-circle-fill.svg';
export { ReactComponent as IconMehFill } from './assets/meh-fill.svg';
export { ReactComponent as IconPlayCircleFill } from './assets/play-circle-fill.svg';
export { ReactComponent as IconPoundCircleFill } from './assets/Pound-circle-fill.svg';
export { ReactComponent as IconSmileFill } from './assets/smile-fill.svg';
export { ReactComponent as IconStopFill } from './assets/stop-fill.svg';
export { ReactComponent as IconWarningCircleFill } from './assets/warning-circle-fill.svg';
export { ReactComponent as IconTimeCircleFill } from './assets/time-circle-fill.svg';
export { ReactComponent as IconTrademarkCircleFil } from './assets/trademark-circle-fil.svg';
export { ReactComponent as IconYUANCircleFill } from './assets/YUAN-circle-fill.svg';
export { ReactComponent as IconHeartFill } from './assets/heart-fill.svg';
export { ReactComponent as IconPieChartCircleFil } from './assets/pie chart-circle-fil.svg';
export { ReactComponent as IconDashboardFill } from './assets/dashboard-fill.svg';
export { ReactComponent as IconMessageFill } from './assets/message-fill.svg';
export { ReactComponent as IconCheckSquareFill } from './assets/check-square-fill.svg';
export { ReactComponent as IconDownSquareFill } from './assets/down-square-fill.svg';
export { ReactComponent as IconMinusSquareFill } from './assets/minus-square-fill.svg';
export { ReactComponent as IconCloseSquareFill } from './assets/close-square-fill.svg';
export { ReactComponent as IconCodeLibraryFill } from './assets/code library-fill.svg';
export { ReactComponent as IconLeftSquareFill } from './assets/left-square-fill.svg';
export { ReactComponent as IconPlaySquareFill } from './assets/play-square-fill.svg';
export { ReactComponent as IconUpSquareFill } from './assets/up-square-fill.svg';
export { ReactComponent as IconRightSquareFill } from './assets/right-square-fill.svg';
export { ReactComponent as IconPlusSquareFill } from './assets/plus-square-fill.svg';
export { ReactComponent as IconAccountBookFill } from './assets/account book-fill.svg';
export { ReactComponent as IconCarryOutFill } from './assets/carry out-fill.svg';
export { ReactComponent as IconCalendarFill } from './assets/calendar-fill.svg';
export { ReactComponent as IconCalculatorFill } from './assets/calculator-fill.svg';
export { ReactComponent as IconInterationFill } from './assets/interation-fill.svg';
export { ReactComponent as IconProjectFill } from './assets/project-fill.svg';
export { ReactComponent as IconDetailFill } from './assets/detail-fill.svg';
export { ReactComponent as IconSaveFill } from './assets/save-fill.svg';
export { ReactComponent as IconWalletFill } from './assets/wallet-fill.svg';
export { ReactComponent as IconControlFill } from './assets/control-fill.svg';
export { ReactComponent as IconLayoutFill } from './assets/layout-fill.svg';
export { ReactComponent as IconAppStoreFill } from './assets/app store-fill.svg';
export { ReactComponent as IconMobileFill } from './assets/mobile-fill.svg';
export { ReactComponent as IconTabletFill } from './assets/tablet-fill.svg';
export { ReactComponent as IconBookFill } from './assets/book-fill.svg';
export { ReactComponent as IconRedEnvelopeFill } from './assets/red envelope-fill.svg';
export { ReactComponent as IconSafetyCertificateF } from './assets/safety certificate-f.svg';
export { ReactComponent as IconPropertySafetyFill } from './assets/property safety-fill.svg';
export { ReactComponent as IconInsuranceFill } from './assets/insurance-fill.svg';
export { ReactComponent as IconSecurityScanFill } from './assets/security scan-fill.svg';
export { ReactComponent as IconFileExclamationFil } from './assets/file-exclamation-fil.svg';
export { ReactComponent as IconFileAddFill } from './assets/file-add-fill.svg';
export { ReactComponent as IconFileFill } from './assets/file-fill.svg';
export { ReactComponent as IconFileExcelFill } from './assets/file-excel-fill.svg';
export { ReactComponent as IconFileMarkdownFill } from './assets/file-markdown-fill.svg';
export { ReactComponent as IconFileTextFill } from './assets/file-text-fill.svg';
export { ReactComponent as IconFilePptFill } from './assets/file-ppt-fill.svg';
export { ReactComponent as IconFileUnknownFill } from './assets/file-unknown-fill.svg';
export { ReactComponent as IconFileWordFill } from './assets/file-word-fill.svg';
export { ReactComponent as IconFileZipFill } from './assets/file-zip-fill.svg';
export { ReactComponent as IconFilePdfFill } from './assets/file-pdf-fill.svg';
export { ReactComponent as IconFileImageFill } from './assets/file-image-fill.svg';
export { ReactComponent as IconDiffFill } from './assets/diff-fill.svg';
export { ReactComponent as IconFileCopyFill } from './assets/file-copy-fill.svg';
export { ReactComponent as IconSnippetsFill } from './assets/snippets-fill.svg';
export { ReactComponent as IconBatchFoldingFill } from './assets/batch folding-fill.svg';
export { ReactComponent as IconReconciliationFill } from './assets/reconciliation-fill.svg';
export { ReactComponent as IconFolderAddFill } from './assets/folder-add-fill.svg';
export { ReactComponent as IconFolderFill } from './assets/folder-fill.svg';
export { ReactComponent as IconFolderOpenFill } from './assets/folder-open-fill.svg';
export { ReactComponent as IconDatabaseFill } from './assets/database-fill.svg';
export { ReactComponent as IconContainerFill } from './assets/container-fill.svg';
export { ReactComponent as IconSeverFill } from './assets/sever-fill.svg';
export { ReactComponent as IconCalendarCheckFill } from './assets/calendar-check-fill.svg';
export { ReactComponent as IconImageFill } from './assets/image-fill.svg';
export { ReactComponent as IconIdCardFill } from './assets/id card-fill.svg';
export { ReactComponent as IconCreditCardFill } from './assets/credit card-fill.svg';
export { ReactComponent as IconFundFill } from './assets/fund-fill.svg';
export { ReactComponent as IconReadFill } from './assets/read-fill.svg';
export { ReactComponent as IconContactsFill } from './assets/contacts-fill.svg';
export { ReactComponent as IconDeleteFill } from './assets/delete-fill.svg';
export { ReactComponent as IconNotificationFill } from './assets/notification-fill.svg';
export { ReactComponent as IconFlagFill } from './assets/flag-fill.svg';
export { ReactComponent as IconMoneyCollectFill } from './assets/money collect-fill.svg';
export { ReactComponent as IconMedicineBoxFill } from './assets/medicine box-fill.svg';
export { ReactComponent as IconRestFill } from './assets/rest-fill.svg';
export { ReactComponent as IconShoppingFill } from './assets/shopping-fill.svg';
export { ReactComponent as IconSkinFill } from './assets/skin-fill.svg';
export { ReactComponent as IconVideoFill } from './assets/video-fill.svg';
export { ReactComponent as IconSoundFill } from './assets/sound-fill.svg';
export { ReactComponent as IconBulbFill } from './assets/bulb-fill.svg';
export { ReactComponent as IconBellFill } from './assets/bell-fill.svg';
export { ReactComponent as IconFilterFill } from './assets/filter-fill.svg';
export { ReactComponent as IconFireFill } from './assets/fire-fill.svg';
export { ReactComponent as IconFunnelPlotFill } from './assets/funnel plot-fill.svg';
export { ReactComponent as IconGiftFill } from './assets/gift-fill.svg';
export { ReactComponent as IconHourglassFill } from './assets/hourglass-fill.svg';
export { ReactComponent as IconHomeFill } from './assets/home-fill.svg';
export { ReactComponent as IconTrophyFill } from './assets/trophy-fill.svg';
export { ReactComponent as IconLocationFill } from './assets/location-fill.svg';
export { ReactComponent as IconCloudFill } from './assets/cloud-fill.svg';
export { ReactComponent as IconCustomerserviceFill } from './assets/customerservice-fill.svg';
export { ReactComponent as IconExperimentFill } from './assets/experiment-fill.svg';
export { ReactComponent as IconEyeFill } from './assets/eye-fill.svg';
export { ReactComponent as IconLikeFill } from './assets/like-fill.svg';
export { ReactComponent as IconLockFill } from './assets/lock-fill.svg';
export { ReactComponent as IconUnlikeFill } from './assets/unlike-fill.svg';
export { ReactComponent as IconStarFill } from './assets/star-fill.svg';
export { ReactComponent as IconUnlockFill } from './assets/unlock-fill.svg';
export { ReactComponent as IconAlertFill } from './assets/alert-fill.svg';
export { ReactComponent as IconApiFill } from './assets/api-fill.svg';
export { ReactComponent as IconHighlightFill } from './assets/highlight-fill.svg';
export { ReactComponent as IconPhoneFill } from './assets/phone-fill.svg';
export { ReactComponent as IconEditFill } from './assets/edit-fill.svg';
export { ReactComponent as IconPushpinFill } from './assets/pushpin-fill.svg';
export { ReactComponent as IconRocketFill } from './assets/rocket-fill.svg';
export { ReactComponent as IconThunderboltFill } from './assets/thunderbolt-fill.svg';
export { ReactComponent as IconTagFill } from './assets/tag-fill.svg';
export { ReactComponent as IconWrenchFill } from './assets/wrench-fill.svg';
export { ReactComponent as IconTagsFill } from './assets/tags-fill.svg';
export { ReactComponent as IconBankFill } from './assets/bank-fill.svg';
export { ReactComponent as IconCameraFill } from './assets/camera-fill.svg';
export { ReactComponent as IconErrorFill } from './assets/error-fill.svg';
export { ReactComponent as IconCrownFill } from './assets/crown-fill.svg';
export { ReactComponent as IconMailFill } from './assets/mail-fill.svg';
export { ReactComponent as IconCarFill } from './assets/car-fill.svg';
export { ReactComponent as IconPrinterFill } from './assets/printer-fill.svg';
export { ReactComponent as IconShopFill } from './assets/shop-fill.svg';
export { ReactComponent as IconSettingFill } from './assets/setting-fill.svg';
export { ReactComponent as IconUSBFill } from './assets/USB-fill.svg';
export { ReactComponent as IconGoldenFill } from './assets/golden-fill.svg';
export { ReactComponent as IconBuildFill } from './assets/build-fill.svg';
export { ReactComponent as IconBoxPlotFill } from './assets/box plot-fill.svg';
export { ReactComponent as IconSlidersFill } from './assets/sliders-fill.svg';
export { ReactComponent as IconAlibaba } from './assets/alibaba.svg';
export { ReactComponent as IconAntDesign } from './assets/ant design.svg';
export { ReactComponent as IconAntCloud } from './assets/ant-cloud.svg';
export { ReactComponent as IconBehance } from './assets/behance.svg';
export { ReactComponent as IconGooglePlus } from './assets/google plus.svg';
export { ReactComponent as IconMedium } from './assets/medium.svg';
export { ReactComponent as IconGoogle } from './assets/google.svg';
export { ReactComponent as IconIE } from './assets/IE.svg';
export { ReactComponent as IconAmazon } from './assets/amazon.svg';
export { ReactComponent as IconSlack } from './assets/slack.svg';
export { ReactComponent as IconAlipay } from './assets/alipay.svg';
export { ReactComponent as IconTaobao } from './assets/taobao.svg';
export { ReactComponent as IconZhihu } from './assets/zhihu.svg';
export { ReactComponent as IconHTML5 } from './assets/HTML5.svg';
export { ReactComponent as IconLinkedin } from './assets/linkedin.svg';
export { ReactComponent as IconYahoo } from './assets/yahoo.svg';
export { ReactComponent as IconFacebook } from './assets/facebook.svg';
export { ReactComponent as IconSkype } from './assets/skype.svg';
export { ReactComponent as IconCodeSandbox } from './assets/CodeSandbox.svg';
export { ReactComponent as IconChrome } from './assets/chrome.svg';
export { ReactComponent as IconCodepen } from './assets/codepen.svg';
export { ReactComponent as IconAliwangwang } from './assets/aliwangwang.svg';
export { ReactComponent as IconApple } from './assets/apple.svg';
export { ReactComponent as IconAndroid } from './assets/android.svg';
export { ReactComponent as IconSketch } from './assets/sketch.svg';
export { ReactComponent as IconGitlab } from './assets/Gitlab.svg';
export { ReactComponent as IconDribbble } from './assets/dribbble.svg';
export { ReactComponent as IconInstagram } from './assets/instagram.svg';
export { ReactComponent as IconReddit } from './assets/reddit.svg';
export { ReactComponent as IconWindows } from './assets/windows.svg';
export { ReactComponent as IconYuque } from './assets/yuque.svg';
export { ReactComponent as IconYoutube } from './assets/Youtube.svg';
export { ReactComponent as IconGitlabFill } from './assets/Gitlab-fill.svg';
export { ReactComponent as IconDropbox } from './assets/dropbox.svg';
export { ReactComponent as IconDingtalk } from './assets/dingtalk.svg';
export { ReactComponent as IconAndroidFill } from './assets/android-fill.svg';
export { ReactComponent as IconAppleFill } from './assets/apple-fill.svg';
export { ReactComponent as IconHTML5Fill } from './assets/HTML5-fill.svg';
export { ReactComponent as IconWindowsFill } from './assets/windows-fill.svg';
export { ReactComponent as IconQQ } from './assets/QQ.svg';
export { ReactComponent as IconTwitter } from './assets/twitter.svg';
export { ReactComponent as IconSkypeFill } from './assets/skype-fill.svg';
export { ReactComponent as IconWeibo } from './assets/weibo.svg';
export { ReactComponent as IconYuqueFill } from './assets/yuque-fill.svg';
export { ReactComponent as IconYoutubeFill } from './assets/Youtube-fill.svg';
export { ReactComponent as IconYahooFill } from './assets/yahoo-fill.svg';
export { ReactComponent as IconWechatFill } from './assets/wechat-fill.svg';
export { ReactComponent as IconChromeFill } from './assets/chrome-fill.svg';
export { ReactComponent as IconAlipayCircleFill } from './assets/alipay-circle-fill.svg';
export { ReactComponent as IconAliwangwangFill } from './assets/aliwangwang-fill.svg';
export { ReactComponent as IconBehanceCircleFill } from './assets/behance-circle-fill.svg';
export { ReactComponent as IconAmazonCircleFill } from './assets/amazon-circle-fill.svg';
export { ReactComponent as IconCodepenCircleFill } from './assets/codepen-circle-fill.svg';
export { ReactComponent as IconCodeSandboxCircleF } from './assets/CodeSandbox-circle-f.svg';
export { ReactComponent as IconDropboxCircleFill } from './assets/dropbox-circle-fill.svg';
export { ReactComponent as IconGithubFill } from './assets/github-fill.svg';
export { ReactComponent as IconDribbbleCircleFill } from './assets/dribbble-circle-fill.svg';
export { ReactComponent as IconGooglePlusCircleF } from './assets/google plus-circle-f.svg';
export { ReactComponent as IconMediumCircleFill } from './assets/medium-circle-fill.svg';
export { ReactComponent as IconQQCircleFill } from './assets/QQ-circle-fill.svg';
export { ReactComponent as IconIECircleFill } from './assets/IE-circle-fill.svg';
export { ReactComponent as IconGoogleCircleFill } from './assets/google-circle-fill.svg';
export { ReactComponent as IconDingtalkCircleFill } from './assets/dingtalk-circle-fill.svg';
export { ReactComponent as IconSketchCircleFill } from './assets/sketch-circle-fill.svg';
export { ReactComponent as IconSlackCircleFill } from './assets/slack-circle-fill.svg';
export { ReactComponent as IconTwitterCircleFill } from './assets/twitter-circle-fill.svg';
export { ReactComponent as IconTaobaoCircleFill } from './assets/taobao-circle-fill.svg';
export { ReactComponent as IconWeiboCircleFill } from './assets/weibo-circle-fill.svg';
export { ReactComponent as IconZhihuCircleFill } from './assets/zhihu-circle-fill.svg';
export { ReactComponent as IconRedditCircleFill } from './assets/reddit-circle-fill.svg';
export { ReactComponent as IconAlipaySquareFill } from './assets/alipay-square-fill.svg';
export { ReactComponent as IconDingtalkSquareFill } from './assets/dingtalk-square-fill.svg';
export { ReactComponent as IconCodeSandboxSquareF } from './assets/CodeSandbox-square-f.svg';
export { ReactComponent as IconBehanceSquareFill } from './assets/behance-square-fill.svg';
export { ReactComponent as IconAmazonSquareFill } from './assets/amazon-square-fill.svg';
export { ReactComponent as IconCodepenSquareFill } from './assets/codepen-square-fill.svg';
export { ReactComponent as IconDribbbleSquareFill } from './assets/dribbble-square-fill.svg';
export { ReactComponent as IconDropboxSquareFill } from './assets/dropbox-square-fill.svg';
export { ReactComponent as IconFacebookFill } from './assets/facebook-fill.svg';
export { ReactComponent as IconGooglePlusSquareF } from './assets/google plus-square-f.svg';
export { ReactComponent as IconGoogleSquareFill } from './assets/google-square-fill.svg';
export { ReactComponent as IconInstagramFill } from './assets/instagram-fill.svg';
export { ReactComponent as IconIESquareFill } from './assets/IE-square-fill.svg';
export { ReactComponent as IconMediumSquareFill } from './assets/medium-square-fill.svg';
export { ReactComponent as IconLinkedinFill } from './assets/linkedin-fill.svg';
export { ReactComponent as IconQQSquareFill } from './assets/QQ-square-fill.svg';
export { ReactComponent as IconRedditSquareFill } from './assets/reddit-square-fill.svg';
export { ReactComponent as IconTwitterSquareFill } from './assets/twitter-square-fill.svg';
export { ReactComponent as IconSketchSquareFill } from './assets/sketch-square-fill.svg';
export { ReactComponent as IconSlackSquareFill } from './assets/slack-square-fill.svg';
export { ReactComponent as IconTaobaoSquareFill } from './assets/taobao-square-fill.svg';
export { ReactComponent as IconWeiboSquareFill } from './assets/weibo-square-fill.svg';
export { ReactComponent as IconZhihuSquareFill } from './assets/zhihu-square-fill.svg';
export { ReactComponent as IconZoomOut } from './assets/zoom out.svg';
export { ReactComponent as IconApartment } from './assets/apartment.svg';
export { ReactComponent as IconAudio } from './assets/audio.svg';
export { ReactComponent as IconAudioFill } from './assets/audio-fill.svg';
export { ReactComponent as IconRobot } from './assets/robot.svg';
export { ReactComponent as IconZoomIn } from './assets/zoom in.svg';
export { ReactComponent as IconRobotFill } from './assets/robot-fill.svg';
export { ReactComponent as IconBugFill } from './assets/bug-fill.svg';
export { ReactComponent as IconBug } from './assets/bug.svg';
export { ReactComponent as IconAudioStatic } from './assets/audio static.svg';
export { ReactComponent as IconComment } from './assets/comment.svg';
export { ReactComponent as IconSignalFill } from './assets/signal-fill.svg';
export { ReactComponent as IconVerified } from './assets/verified.svg';
export { ReactComponent as IconShortcutFill } from './assets/shortcut-fill.svg';
export { ReactComponent as IconVideocameraAdd } from './assets/videocamera add.svg';
export { ReactComponent as IconSwitchUser } from './assets/switch user.svg';
export { ReactComponent as IconWhatsapp } from './assets/whatsapp.svg';
export { ReactComponent as IconAppstoreAdd } from './assets/appstore add.svg';
export { ReactComponent as IconCaretDown } from './assets/caret-down.svg';
export { ReactComponent as IconBackward } from './assets/backward.svg';
export { ReactComponent as IconCaretUp } from './assets/caret-up.svg';
export { ReactComponent as IconCaretRight } from './assets/caret-right.svg';
export { ReactComponent as IconCaretLeft } from './assets/caret-left.svg';
export { ReactComponent as IconFastBackward } from './assets/fast-backward.svg';
export { ReactComponent as IconForward } from './assets/forward.svg';
export { ReactComponent as IconFastForward } from './assets/fast-forward.svg';
export { ReactComponent as IconSearch } from './assets/search.svg';
export { ReactComponent as IconRetweet } from './assets/retweet.svg';
export { ReactComponent as IconLogin } from './assets/login.svg';
export { ReactComponent as IconStepBackward } from './assets/step-backward.svg';
export { ReactComponent as IconStepForward } from './assets/step-forward.svg';
export { ReactComponent as IconSwapRight } from './assets/swap-right.svg';
export { ReactComponent as IconSwapLeft } from './assets/swap-left.svg';
export { ReactComponent as IconWoman } from './assets/woman.svg';
export { ReactComponent as IconPlus } from './assets/plus.svg';
export { ReactComponent as IconEyeCloseFill } from './assets/eye close-fill.svg';
export { ReactComponent as IconEyeClose } from './assets/eye-close.svg';
export { ReactComponent as IconClear } from './assets/clear.svg';
export { ReactComponent as IconCollapse } from './assets/collapse.svg';
export { ReactComponent as IconExpand } from './assets/expand.svg';
export { ReactComponent as IconDeleteColumn } from './assets/delete column.svg';
export { ReactComponent as IconMergeCells } from './assets/merge-cells.svg';
export { ReactComponent as IconSubnode } from './assets/subnode.svg';
export { ReactComponent as IconRotateLeft } from './assets/rotate-left.svg';
export { ReactComponent as IconRotateRight } from './assets/rotate-right.svg';
export { ReactComponent as IconInsertRowBelow } from './assets/insert row below.svg';
export { ReactComponent as IconInsertRowAbove } from './assets/insert row above.svg';
export { ReactComponent as IconSolitCells } from './assets/solit-cells.svg';
export { ReactComponent as IconFormatPainter } from './assets/format painter.svg';
export { ReactComponent as IconInsertRowRight } from './assets/insert row right.svg';
export { ReactComponent as IconFormatPainterFill } from './assets/format painter-fill.svg';
export { ReactComponent as IconInsertRowLeft } from './assets/insert row left.svg';
export { ReactComponent as IconTranslate } from './assets/translate.svg';
export { ReactComponent as IconDeleteRow } from './assets/delete row.svg';
export { ReactComponent as IconSisternode } from './assets/sisternode.svg';
export { ReactComponent as IconFieldNumber } from './assets/Field-number.svg';
export { ReactComponent as IconFieldString } from './assets/Field-String.svg';
export { ReactComponent as IconFunction } from './assets/Function.svg';
export { ReactComponent as IconFieldTime } from './assets/Field-time.svg';
export { ReactComponent as IconGIF } from './assets/GIF.svg';
export { ReactComponent as IconPartition } from './assets/Partition.svg';
export { ReactComponent as IconIndex } from './assets/index.svg';
export { ReactComponent as IconStoredProcedure } from './assets/Stored procedure.svg';
export { ReactComponent as IconFieldBinary } from './assets/Field-Binary.svg';
export { ReactComponent as IconConsoleSQL } from './assets/Console-SQL.svg';
export { ReactComponent as Icon11 } from './assets/1:1.svg';
export { ReactComponent as IconAim } from './assets/aim.svg';
export { ReactComponent as IconCompress } from './assets/compress.svg';
export { ReactComponent as IconExpend } from './assets/expend.svg';
export { ReactComponent as IconFolderView } from './assets/folder-view.svg';
export { ReactComponent as IconFileGIF } from './assets/file-GIF.svg';
export { ReactComponent as IconGroup } from './assets/group.svg';
export { ReactComponent as IconSend } from './assets/send.svg';
export { ReactComponent as IconReport } from './assets/Report.svg';
export { ReactComponent as IconView } from './assets/View.svg';
export { ReactComponent as IconShortcut } from './assets/shortcut.svg';
export { ReactComponent as IconUngroup } from './assets/ungroup.svg';
